# Title, decription, tagline and URL for your site
# Can be used in your theme by calling 'site.title' and so on
title: PS212
description: We are a strategic brand consultancy with big agency experience, operating at start-up speed.
url: http://www.ps212.com

# CloudCannon uses these:
source: src
destination: dist
exclude:

collections:
  projects:
    output: true
    permalink: /work/:slug/
  people:
    output: true
    permalink: /about/:slug/
defaults:
  -
    scope:
      path: ""
      type: projects
    values:
      class: project
      layout: project
  -
    scope:
      path: ""
      type: people
    values:
      class: about
      layout: about
  -
    scope:
      path: "cms.md"
    values:
      layout: "cms"
      permalink: "/cms/"
      _hide_content: true
  -
    scope:
      path: "about.html"
    values:
      class: about
      layout: default
      permalink: "/about/"


# Extending Jekyll
gems:
  - jekyll-sitemap
  - jekyll-seo-tag
  # - jekyll-redirect-from
  # - jekyll-polyglot
  # - jekyll-paginate
  # - jekyll-archives
  # - jekyll-feed
